development:
  adapter: mysql2
  database: kkdd_development
  username: root
  password: password
  host: localhost
  encoding: utf8

test:
  adapter: mysql2
  database: kkdd_test
  username: root
  password: password
  host: localhost
  encoding: utf8